os: linux
dist: bionic
# Python is required to run `doc_status.py`.
language: python

python:
  - 3.8

env:
  - HUGO_VERSION="0.76.3"

install:
  - curl -LO "https://github.com/gohugoio/hugo/releases/download/v$HUGO_VERSION/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz"
  - tar xf "hugo_${HUGO_VERSION}_Linux-64bit.tar.gz" hugo
  - sudo mv hugo /usr/local/bin/

script:
  - ./build.sh

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  token: $GITHUB_TOKEN
  target_branch: gh-pages

  # Only deploy from the `master` branch.
  on:
    branch: master
