baseURL = "https://godotengine.github.io/doc-status/"
languageCode = "en-us"
title = "Godot class reference status"

# This is a single-page website, no need to generate a sitemap and RSS feed.
disableKinds = ["sitemap", "RSS", "taxonomyTerm"]

[markup.goldmark.renderer]
  unsafe = true
